---
- hosts: all
  become: true
  vars:
    vsftpd_anon_root: /srv/shares/public
    vsftpd_local_enable: true
    vsftpd_local_root: /srv/shares/private
    vsftpd_options:
      - key: delete_failed_uploads
        value: 'YES'
      - key: ftpd_banner
        value: "Welcome to the FTP service"
  roles:
    - vsftpd
  post_tasks:
    - name: Put a demo file in the anonymous directory
      copy:
        dest: '{{ vsftpd_anon_root }}/README'
        content: 'anon_root'
    - name: Put a demo file in the user directory
      copy:
        dest: '{{ vsftpd_local_root }}/README'
        content: 'local_root'
    - name: Restart network (workaround for Vagrant bug 8096)
      # See https://github.com/mitchellh/vagrant/issues/8096
      service:
        name: network
        state: restarted
      when: ansible_os_family == 'RedHat'
    - name: Ensure firewall is not running
      service:
        name: firewalld
        state: stopped
      when: ansible_os_family == 'RedHat'
    - name: Add user for testing authenticated access
      user:
        name: alice
        state: present
        password: '$6$vNPq5eom$xCeXlUBGlXqZB5Mj1J1Ts3xb/e8TBYix6o73HlkCCrGF8r4rPSMM2yavNqEg2RPUYgoqTuWEb3I07HJR48OxB1'
        # alice
